apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "nvidia-powerai.fullname" . }}
  labels:
    app: {{ template "nvidia-powerai.name" . }}
    chart: {{ template "nvidia-powerai.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "nvidia-powerai.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nvidia-powerai.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ssh-powerai 
              containerPort: 22 
              protocol: TCP
          resources:
          volumeMounts:
            - name: datavol
              mountPath: /home
      volumes:
      - name: datavol
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-{{ .Values.name }}"
