apiVersion: v1
kind: Service
metadata:
  #name: {{ template "nvidia-powerai.name" . }}
  name: {{ .Release.Name }}-{{ template "nvidia-powerai.name" . }} 
  labels:
    app: {{ template "nvidia-powerai.name" . }}
    chart: {{ template "nvidia-powerai.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22 
      protocol: TCP
      name: ssh-powerai 
  externalIPs:
    - 10.3.50.31


  selector:
    app: {{ template "nvidia-powerai.name" . }}
    release: {{ .Release.Name }}
