# Default values for nvidia-powerai.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: nvidia-powerai
replicaCount: 1

image:
  repository: mycluster.icp:8500/test-namespace/powerai-152  
  tag: 0.1 
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 22 
  externalIPs:
    - 10.3.50.31

ingress:
  enabled: false
  annotations: {}
 # kubernetes.io/ingress.class: nginx
  #kubernetes.io/tls-acme: "true"
  path: /aivision
  hosts:
    - example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
#  gpu: 0   
# We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
    gpu: 0
  requests:
    cpu: 100m
    memory: 128Mi
    gpu: 0
nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: ""
fullnameOverride: ""

## global persistence parameters
persistence:
  enabled: true
  useDynamicProvisioning: false
  storageClass: ""
  accessMode: ReadWriteMany 
  size: 10Gi 

#databasePVC:
#  name: "powerai-pvc"
#  ## specify the storageClassName you want to use
  ## if you don't specify a storageClassName it will use the default
#  storageClass: ""
#  storageClassName: ""
  ## Specify the name of the Existing Claim to be used by your application
  ## empty string means don't use an existClaim
#  existingClaimName: ""
#  size: 10Gi

license: "not accepted"
